### ISSUE TITLE
wechat@2.6.8: hash check failed

### ISSUE THREAD

**Issue by TTtrace** [h404bi/dorado#10]
Download: Status Legend:
Download: (OK):download completed.
Checking hash of WeChatSetup.exe ... ERROR Hash check failed!
App:         dorado/wechat
URL:         https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    fb77dd957bd07afae84ca144d7fd334447a5bc983bb25a4046dd3afaf467bfc3
Actual:      e84740348b91a18891ff0b8c5799138dc2a21fe9205733d98c7c36c32a7a5399

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/h404bi/dorado/issues/new?title=wechat%402.6.8%3a+hash+check+failed

It seems that this kind of issue had been closed, but this problem is still here.

**Comment by h404bi** [comment]
The installer often changes, without a fixed version. I changed the version to `nightly`.
