### ISSUE TITLE
Autoupdate Robot

### ISSUE THREAD

**Issue by h404bi** [h404bi/dorado#12]
https://github.com/ScoopInstaller/Excavator

**Comment by Ash258** [comment]
If you do not have own server / device which could run this 24/7, you can test new [github actions](https://github.com/features/actions). (You need to sign up for beta, but you should receive feature soon.)

Then you can do simple:

```hcl
#/.github/bucket.workflow
workflow "Excavator" {
  on = "schedule(0 * * * *)"
  resolves = ["Excavate"]
}

action "Excavate" {
  uses = "Ash258/Scoop-GithubActions@0.3.58"
  args = "Scheduled"
  env = {
      "GITH_EMAIL" = "youremail@email.com"
  }
  secrets = ["GITHUB_TOKEN"]
}
```
https://github.com/Ash258/GithubActionsBucketForTesting/runs/155116934

**Comment by h404bi** [comment]
Sounds great, I've added the workflow, signed up for GitHub Actions. Now waiting for it.

**Comment by h404bi** [comment]
@Ash258 The GitHub Action ends with pushing failure. 
https://github.com/h404bi/dorado/commit/4691cba90562f00f0a6fbae8617f43b61bd3b360/checks#step:4:290

**Comment by Ash258** [comment]
Ash258/Scoop-GithubActions#45

**Comment by h404bi** [comment]
Ok...

**Comment by Ash258** [comment]
Good news. Just pushed fix to stable. 

Do you have protected master? I do not know if current fix will be working on protected masters, but for normal branches it is working

https://github.com/Ash258/GithubActionsBucketForTesting/commit/e377953ba5552613b185ca3d77b5321c682f3a77/checks#step:4:99

**Comment by h404bi** [comment]
Yes, the branch is protected. https://github.com/h404bi/dorado/commit/4691cba90562f00f0a6fbae8617f43b61bd3b360/checks#step:4:204

**Comment by Ash258** [comment]
I suspect that this is something I cannot bypass with universal way.

I think custom secrret with SSH key could do the trick, but do not have time right now to test.

**Comment by kidonng** [comment]
@h404bi https://github.com/Ash258/Scoop-GithubActions/issues/45#issuecomment-528509575
