### ISSUE TITLE
epicgameslauncher 无法启动

### ISSUE THREAD

**Issue by fiammanda** [h404bi/dorado#121]
epicgameslauncher 提示缺少xinput1_3.dll和d3dcompiler_43，下载放入binary文件夹后仍然提示程序错误

**Comment by h404bi** [comment]
是不是系统没打 DirectX 补丁。

**Comment by fiammanda** [comment]
> 
> 
> 是不是系统没打 DirectX 补丁。

是的是的，重装之后忘了没装（。
