### ISSUE TITLE
nuwen-mingw-without-git 环境疑问

### ISSUE THREAD

**Issue by Gaaraly** [h404bi/dorado#123]
安装以后是需要手动配置吧？如果需要在terminal里使用，需要先 mingw on后，才能调用gcc。重启terminal后环境又无了，如果需要直接调用是需要手动添加环境变量吧？

**Comment by h404bi** [comment]
是的，环境开关只对当前 terminal session 有效，新开 session 要重新 set on。

环境开关脚本在这里：
https://github.com/h404bi/dorado/blob/edff1b37f9bd4ae8875e114630fb2975ae007e52/scripts/nuwen-mingw-without-git/nuwen_path_helper.ps1

脚本目前还不完善，计划是能持久化环境变量，并且能在非 powershell 的 session 下也能用。

之前默认是直接在安装时由 scoop 强制配置环境变量的，这样的问题是 PATH 污染比较厉害，想去掉只能卸载。我想提供一个 feature 可以根据需要去开关环境，这样遇到问题时能关掉，不用卸载。

现在这个可能用起来不太友好。欢迎 feedback。

**Comment by Gaaraly** [comment]
> 是的，环境开关只对当前 terminal session 有效，新开 session 要重新 set on。
> 
> 环境开关脚本在这里：
> https://github.com/h404bi/dorado/blob/edff1b37f9bd4ae8875e114630fb2975ae007e52/scripts/nuwen-mingw-without-git/nuwen_path_helper.ps1
> 
> 脚本目前还不完善，计划是能持久化环境变量，并且能在非 powershell 的 session 下也能用。
> 
> 之前默认是直接在安装时由 scoop 强制配置环境变量的，这样的问题是 PATH 污染比较厉害，想去掉只能卸载。我想提供一个 feature 可以根据需要去开关环境，这样遇到问题时能关掉，不用卸载。
> 
> 现在这个可能用起来不太友好。欢迎 feedback。

感谢您的奉献。持久化环境变量确实能方便很多，使用VScode配置C++也相对更简单，目前体验只能在命令行进行操作不太方便，也希望能早点实现feature。
ps:看一眼自己电脑发现path污染还真挺严重的😂

**Comment by h404bi** [comment]
https://github.com/h404bi/dorado/commit/423a095f0b354bf74db6920fab843f3e8b072135
我完善了一下 env 脚本，现在 mingw on 后环境变量可以持久化了，能被 vscode 等编辑器识别。

**Comment by Gaaraly** [comment]
感谢，很方便😄
