### ISSUE TITLE
[Request] 大佬 能否添加FluentTerminal 谢谢

### ISSUE THREAD

**Issue by zhoujin7** [h404bi/dorado#23]
**FluentTerminal**
https://github.com/felixse/FluentTerminal

**Comment by h404bi** [comment]
粗看了一下，大概需要提权安装（主要在[自签证书安装](https://github.com/felixse/FluentTerminal#manual-install)步骤上），这不太符合本 bucket [宗旨](https://github.com/h404bi/dorado/blob/master/README_CN.md)。如有其他用户找到无需管理员权限安装流程的话，欢迎贡献。

**Comment by zhoujin7** [comment]
坐等windows terminal完善
