### ISSUE TITLE
[Request]能否支持下aapt2，顺便帮忙修改下psping

### ISSUE THREAD

**Issue by Nexus2018** [h404bi/dorado#29]
参考tcping自己弄了个psping，这个psping上次更新还是再2016年，估计微软也懒得再更新，不知道应该怎么写更新内容。
{
    "homepage": "https://docs.microsoft.com/en-us/sysinternals/downloads/pstools",
    "description": "The PsTools suite includes command-line utilities for listing the processes running on local or remote computers, running processes remotely, rebooting computers, dumping event logs, and more.",
    "version": "2.45",
    "license": "GPL-2.0-only",
    "url": "https://download.sysinternals.com/files/PSTools.zip",
    "hash": "B9F404D4C7B6BF3A37746C66BCD014E75859D2FCF887B1DB527EC3ED2CCDEB30",
    "bin": [
        "psping.exe"
    ]
}

aapt2需要怎么获取最新的版本名。
参考页面https://developer.android.google.cn/studio/command-line/aapt2#download_aapt2

**Comment by h404bi** [comment]
pstools: https://github.com/h404bi/dorado/commit/62785b863f6d6b3b502d93602b3c02bb5c4b0f37
看了下 aapt2 是一个 jar，是 ADK 里的工具，单独拆出来可用吗？没怎么了解过 Android Dev。

**Comment by Nexus2018** [comment]
使用7zip直接解压出来就可以使用。
文件结构如下
|   aapt2.exe
|   libwinpthread-1.dll
|   NOTICE
|   
\---META-INF
        MANIFEST.MF

需要把aapt2.exe添加到环境变量中。

**Comment by h404bi** [comment]
用了 https://mvnrepository.com/artifact/com.android.tools.build/aapt2 来检测新版本。
