### ISSUE TITLE
If you use this bucket, give a thumbs up and let me know!

### ISSUE THREAD

**Issue by h404bi** [h404bi/dorado#3]
Awesome!

**Comment by zhoujin7** [comment]
@chawyehsu 老哥你的邮箱是这个吗? chawyehsu【at】hotmail。com 我发邮件给你了

**Comment by amorphobia** [comment]
Hi 作者!

这几天我发现 scoop bucket 仓库的 "Tests" action 总是在 "WindowsPowerShell" 任务失败，而 "PowerShell" 任务能够成功，您的这个仓库貌似也这样。是上游仓库有什么改动吗？

Thanks!
