### ISSUE TITLE
[Request] 支持WPS

### ISSUE THREAD

**Issue by xuhuanfeng** [h404bi/dorado#30]
Hi，请问能否支持下金山WPS呢？

由于某些原因，缺乏权限安装WPS，

请问能否有办法去除相关权限或者由类似的思路可以提供呢？

[WPS下载地址](https://pacakge.cache.wpscdn.cn/wps/download/W.P.S.9098.12012.2019.exe)

**Comment by h404bi** [comment]
尝试了一下，有解包免安装的可能，但是有点限制。目前思路如下。
1、从 WPS 官网下载到的 exe 安装程序，可以直接通过 7zip 解压缩得出以下目录树文件：
```
+---$PLUGINSDIR
|       EnumINI.dll
|       FindProcDLL.dll
|       System.dll
|       v6svc_oem.dll
|
\---$_11_
    |   $EXEFILE
    |   oem.ini
    |   oem_enterprise.txt
    |   oem_static.exe
    |
    \---oeminfo
            oem.exe
```
2、7zip 解压出来的文件中，`$_11_\$EXEFILE` 这个文件没有后缀，但看名字就知道是 exe，可以改后缀为 exe，点开是可以执行的。这个文件实际上就是最终的安装程序。但是安装还是需要管理员权限。
![20191007121000](https://user-images.githubusercontent.com/5764917/66284662-77736f80-e8fb-11e9-9344-e56ca7f111c8.png)
3、用 7zip 打开 `$_11_\$EXEFILE`，只能看到有一个 `CONTROL` 的目录。里面很多文件，不过并不是 WPS 本体，这些文件只是 WPS 安装器（installer）的文件。
![20191007121130](https://user-images.githubusercontent.com/5764917/66284695-9bcf4c00-e8fb-11e9-8e94-53a0b729a8ee.png)
4、回到解压缩的目录，用 7zip 的另一种打开方式 `Open inside #` 再次打开 `$_11_\$EXEFILE`。
![20191007120822](https://user-images.githubusercontent.com/5764917/66284651-704c6180-e8fb-11e9-9a26-7bb7d98552fd.png)
5、这次会看到有几个文件，其中两个是 7z 压缩包。这 2 个 7z 包，第一个（2.7z）是 WPS 安装器，而第 2 个（4.7z），就是 WPS 本体的全部文件。
![20191007121308](https://user-images.githubusercontent.com/5764917/66284734-d802ac80-e8fb-11e9-9d0c-520df818a6fa.png)
![20191007121505](https://user-images.githubusercontent.com/5764917/66284779-1ef0a200-e8fc-11e9-876b-d13d15342214.png)
6、将 4.7z 提取出来，并解压缩，就能得到 WPS 本体执行程序。`\$_11_\$EXEFILE\4.7z\office6\wps.exe`。可以以普通用户启动，正常运行。但是不会有文件关联。
![20191007121840](https://user-images.githubusercontent.com/5764917/66284861-9c1c1700-e8fc-11e9-9959-3511027bf5ac.png)

以上是调查到的过程，测试 wps.com 国际版流程一样。能力有限，目前我无法用 Scoop 做成自动化（主要受限在前述第 4 步骤）。欢迎有能力者贡献。

**Comment by xuhuanfeng** [comment]
嗯嗯，按照你提供的思路，我试验了一下，核心功能都能使用，不过像登录啊这些不好使，估计是那个安装器本身会去执行一些注册表操作之类的

辛苦大大了

**Comment by linsui** [comment]
之前尝试过，没想到还有第4步这种方式。

```
{
    "version": "11.2.0.8991",
    "homepage": "https://www.wps.com",
    "description": "Complete office suite.",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.wps.com/eula"
    },
    "url": "http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/11.2.0.8991/WPSOffice_11.2.0.8991.exe#/dl.7z",
    "hash": "0aa4a4de7e89ac4bddae138ffd2c0e74ad8f90f6c737b813e78e9d75af577fc0",
    "extract_dir": "$_11_",
    "pre_install": [
        "Expand-7zipArchive \"$dir\\`$EXEFILE\" -Switches '-t#'",
        "Remove-Item \"$dir\\*\" -Exclude '4.7z' -Recurse",
        "Expand-7zipArchive \"$dir\\4.7z\" -ExtractDir 'office6' -Removal"
    ],
    "bin": "wpsoffice.exe",
    "shortcuts": [
        [
            "wpsoffice.exe",
            "WPS 2019"
        ]
    ],
    "checkver": {
        "url": "https://pc.wps.com",
        "regex": "WPSOffice_([\\d.]+)\\.exe"
    },
    "autoupdate": {
        "url": "http://wdl1.pcfg.cache.wpscdn.com/wpsdl/wpsoffice/download/$version/WPSOffice_$version.exe#/dl.7z",
        "extract_dir": "$_$majorVersion_"
    }
}
```

**Comment by h404bi** [comment]
@linsui 棒！你能做个中文版的发个PR吗？

**Comment by linsui** [comment]
中文版应该改一下 url 就可以 :joy: 我没测试就不 PR 了

**Comment by linsui** [comment]
这是中文版

```
{
    "version": "11.1.0.9175",
    "homepage": "https://pc.wps.cn",
    "description": "Complete office suite.",
    "license": {
        "identifier": "Freeware",
        "url": "https://www.wps.com/eula"
    },
    "url": "https://pacakge.cache.wpscdn.cn/wps/download/W.P.S.9175.12012.2019.exe#/dl.7z",
    "hash": "ca730bce7145c0637c1cfc240f85c5a0d05d8f7610e7e17423b36151241038a9",
    "extract_dir": "$_11_",
    "pre_install": [
        "Expand-7zipArchive \"$dir\\`$EXEFILE\" -Switches '-t#'",
        "Remove-Item \"$dir\\*\" -Exclude '4.7z' -Recurse",
        "Expand-7zipArchive \"$dir\\4.7z\" -ExtractDir 'office6' -Removal"
    ],
    "bin": "wpsoffice.exe",
    "shortcuts": [
        [
            "wpsoffice.exe",
            "WPS Office"
        ]
    ],
    "checkver": "(?sm)W\\.P\\.S\\.(?<num>[\\d.]+)\\.exe.*?verson_txt\">([\\d.]+)",
    "autoupdate": {
        "url": "https://pacakge.cache.wpscdn.cn/wps/download/W.P.S.$matchNum.exe#/dl.7z",
        "extract_dir": "$_$majorVersion_"
    }
}
```
