### ISSUE TITLE
[Request] Any plan to add Texlive?

### ISSUE THREAD

**Issue by tkit1994** [h404bi/dorado#31]
Any plan to add Texlive?
**Please describe the app you want to add.**
App name, description, website, where to download, special note [...]
## App name
Texlive
## description: 
TeX Live is a cross-platform, free software distribution for the TeX typesetting system that includes major TeX-related programs, macro packages, and fonts. It is the replacement of its no-longer supported counterpart teTeX
## website
https://www.tug.org/texlive/

**Comment by h404bi** [comment]
This package is **huge** (3GB+ of the v2019 iso installer), and the installation is complicated with so many customizable install configurations.

This will make me spend more time investigating the installation automation of this application. 

> [install-tl-windows -no-gui -help](https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-180003.1.3)

I don't know much about Tex, it would be appreciated if someone wants to do contributions.

**Comment by h404bi** [comment]
You can now install TexLive with the experimental stage manifest:

```
cd ~/scoop/buckets/dorado
scoop install .\experiment\texlive.json
```

**Note**: This is an EARLY EXPERIMENTAL STAGE manifest, just a minimal installation, no data persistence (I don't know what files should be persisted). Do NOT use it in production.

Please leave your feedback.

**Comment by ret394** [comment]
for smaller size solution try https://miktex.org/download#portable, about 224 MB.

**Comment by h404bi** [comment]
What's the difference between miktex and texlive?

**Comment by chawyehsu** [comment]
I just published a manifest for a full installation of TexLive, https://github.com/chawyehsu/dorado/commit/eb1f9b6c2eea13331f586d2c31e4822a1c35fe9f, which is the latest solution.
