### ISSUE TITLE
[Request] QQ影音

### ISSUE THREAD

**Issue by smshess** [h404bi/dorado#32]
**QQPlayer**

https://player.qq.com/

新版使用还是比较舒服的，目前也没什么作恶的行为。

**Comment by h404bi** [comment]
测试初次打开会弹UAC。使用有问题欢迎反馈。

**Comment by smshess** [comment]
哈哈，电脑默认关闭UAC，从来没注意过这个问题

Chawye Hsu <notifications@github.com> 于2019年10月12日周六 下午11:53写道：
