### ISSUE TITLE
[Request]能否增加Linux中的tree；RunAny等软件

### ISSUE THREAD

**Issue by fandean** [h404bi/dorado#39]
- tree 命令：http://gnuwin32.sourceforge.net/packages/tree.htm
- RunAny 一劳永逸的快速启动软件（绿色压缩包）：https://github.com/hui-Zz/RunAny
- Hbuilderx 好用的编辑器（绿色压缩包）：https://www.dcloud.io/hbuilderx.html
- Rime 一款输入法：https://rime.im/
- PortableApps 收集各种便携软件的平台：https://portableapps.com/zh-cn

**Comment by h404bi** [comment]
- tree. Windows 10 下有 tree 命令了。这个 GNU tree 好像很老了吧。
- RunAny. done.
- Hbuilderx. 哪个版本？
- rime. 输入法还是不要用绿色办法安装了。正常安装需要提权。
- PortableApps. 用户数据不好做持久化。

**Comment by fandean** [comment]
Hbuilderx 需要指定版本，这个我不大理解；不过没关系，常用的RunAny已经添加就非常感谢了。

**Thank you！**
