### ISSUE TITLE
关于scoop的几点疑问

### ISSUE THREAD

**Issue by batkiz** [h404bi/dorado#4]
scoop非常好用，我近日想要将自己常用的几个软件写入一个bucket中，有几点疑问希望能得到解答。

- 对于一些官方未给hash值的软件，其`hash`项应如何获得？自己下载后检验hash值写入，或者有其他手段来获得hash值么？
- 某些软件的配置文件是在目录中的，对这种软件scoop能否进行有效处理？(升级时保留配置文件)

再次感谢您的两篇文章与本Bucket。

**Comment by h404bi** [comment]
1. 没有显式给 hash 的话，在创建 manifest 时，只能自己下载通过 shasum 计算出 hash 手动写入。之后有更新时，可以使用 `\bin\auto-pr.ps1` 进行半自动化，让程序下载计算 hash。（*`bin` 目录下是一些维护 bucket 用到的有用的脚本，都是 scoop 本身提供的，一般维护者在自己的 bucket 下自行封装使用即可，可以自己研究下。*）
2. 数据**持久化**这个在官方 [Wiki](https://github.com/lukesampson/scoop/wiki/Persistent-data) 里有详细的介绍，可以先查看下文档。通常就是在 manifest 里用 `persist` 字段处理要持久化的数据。这里面有些坑点，不过一般不会遇到。

似乎越来越多人接触到 scoop， 仓库更新越来越频繁，bug 和新 feature 不断出现在 scoop 的 issue tracker 中，近段时间总觉得 scoop 不太稳定（至少比以前用起来）。越发希望 scoop 的协作者们能推动 scoop 稳定版相关的事宜，我的文章里也说到这点。不过这都是后话了，祝你使用愉快。
