### ISSUE TITLE
网络问题导致的安装包无法下载，该如何解决？

### ISSUE THREAD

**Issue by fandean** [h404bi/dorado#41]
安装包无法成功下载

```shell
$ scoop install irfanview
Installing 'irfanview' (4.53) [64bit]
Starting download with aria2 ...
Download: [DL:0B][#54d2da 0B/0B][#ff5c5e 0B/0B]
Download: [DL:0B][#54d2da 0B/0B][#ff5c5e 0B/0B]
.
.
Download: [DL:0B][#54d2da 0B/0B][#ff5c5e 0B/0B]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://www.irfanview.info/files/iview453_x64.zip
```
iview453_x64.zip 下载不了，问题在于我可以利用浏览器插件通过浏览器下载该zip，
我在想能否配置scoop从本地电脑（或其他位置）获取该zip，而不是通过 `https://www.irfanview.info/files/iview453_x64.zip `

**Comment by kidonng** [comment]
可以手动下载文件，重命名为 Scoop 指定的格式 `irfanview#4.53#https_www.irfanview.info_files_iview453_x64.zip` 然后扔进 `cache`。

**Comment by zhoujin7** [comment]
@fandean 你配置了scoop代理没有

**Comment by fandean** [comment]
sorry过了这么久才回复
今天尝试了一下 @kidonng 介绍的方法，但是在使用 `scoop install irfanview` 安装时，下载的文件名为

irfanview#4.53#https_www.irfanview.info_files_iview453_plugins_x64.zip

该压缩包中还包含了 plugins，大小有 22MB ，而 irfanview#4.53#https_www.irfanview.info_files_iview453_x64.zip 只有 3MB；幸运的是这次在没有设置任何代理的情况下下载成功了。

---

@zhoujin7 当前我只能通过浏览器可以科学上网；不过为 scoop 配置代理这件事还是愿闻其详。

**Comment by kidonng** [comment]
https://scoop-docs.now.sh/docs/misc/Using-Scoop-behind-a-proxy.html

**Comment by fandean** [comment]
谢谢
