### ISSUE TITLE
[Request] 大佬能否添加https://www.adiirc.com/ irc聊天客户端

### ISSUE THREAD

**Issue by zhoujin7** [h404bi/dorado#54]
**App name** AdiIRC
**description** AdiIRC is a free Internet Relay Chat (IRC) client.
**website** https://www.adiirc.com/
**where to download** https://www.adiirc.com/download.php
**the license** 未知
**special note** 绿色便携软件, 开发活跃, 更新频繁, 比较好用(用的话, 需要微调设置)

**Comment by h404bi** [comment]
https://github.com/h404bi/dorado/blob/12f73f42ae00cab78b978dd10f4accc4d146be33/experiment/adiirc.json

我没用过这个软件，不太清楚有哪些数据文件需要 persistence。有使用的可以反馈一下。

**Comment by zhoujin7** [comment]
好的

**Comment by zhoujin7** [comment]
其他两个我提的 不用搞了 我已经在弄了

**Comment by zhoujin7** [comment]
#55

**Comment by zhoujin7** [comment]
感谢大佬的努力工作 
https://github.com/zhoujin7/tomato/blob/master/bucket/AdiIRC.json
不好意思 我在自己仓库添加了.
