### ISSUE TITLE
[Request]Bilibili Stream Recorder

### ISSUE THREAD

**Issue by Ez4Crithit** [h404bi/dorado#56]
# App name
B站录播姬 - Bilibili Stream Recorder
# description
 一个BiliBili直播录制工具
# website
https://rec.danmuji.org/
https://github.com/Bililive/BililiveRecorder
# download
https://github.com/Bililive/BililiveRecorder/releases
https://soft.danmuji.org/BililiveRecorder/Setup.exe

**Comment by h404bi** [comment]
https://github.com/h404bi/dorado/commit/4fdeccdd1446a47aba4f4cc633e4e4d9f9c98e70
