### ISSUE TITLE
[BUG]officetoolplus下载地址不对

### ISSUE THREAD

**Issue by ghjzeus** [h404bi/dorado#60]
officetoolplus7.3.1.0的下载地址为：       https://github.com/YerongAI/Office-Tool/releases/download/7.3.1.0/Office.Tool.v7.3.zip

**Comment by ghjzeus** [comment]
实验了一下 修改配置如下
    "url": "https://github.com/YerongAI/Office-Tool/releases/download/7.3.1.0/Office.Tool.v7.3.zip",
    "hash": "90f96679f8146433dd89698c78c744453175cabbb7c5fa56ced67e0263eb6681",
    "extract_dir": "Office Tool",

**Comment by h404bi** [comment]
发个 PR 呗
