### ISSUE TITLE
安装网易音乐提示错误，程序已成功安装

### ISSUE THREAD

**Issue by m4wayne** [h404bi/dorado#78]
PS C:\Users\xxx> scoop install neteasemusic
Installing 'neteasemusic' (2.7.1.198242) [64bit]
cloudmusicsetup2.7.1.198242.exe (39.5 MB) [===================================================================] 100%
Checking hash of cloudmusicsetup2.7.1.198242.exe ... ok.
Extracting dl.7z ... done.
Linking D:\Apps\Scoop\User\apps\neteasemusic\current => **D:\Apps\Scoop\User\apps\neteasemusic\2.7.1.198242
管道元素中的“&”后面的表达式生成无效的对象。该表达式必须生成命令名称、脚本块或 CommandInfo 对象。
所在位置 D:\Apps\Scoop\User\apps\scoop\current\lib\install.ps1:881 字符: 7
+     & "$env:COMSPEC" /c mklink /j $currentdir $versiondir | out-null
+       ~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:String) []，RuntimeException
    + FullyQualifiedErrorId : BadExpression

Creating shim for 'cloudmusic'.
Can't shim 'cloudmusic.exe': File doesn't exist.**
PS C:\Users\xxx>

**Comment by h404bi** [comment]
Please post your `$PSVersionTable` and `$env:COMSPEC` information.

**Comment by m4wayne** [comment]
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.628
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.628
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

----------------------------------------------------------------

$env:COMSPEC
empty

**Comment by h404bi** [comment]
> $env:COMSPEC
> empty

Perhaps you need to fix the system environment variables of your PC. `$env:COMSPEC` should point to the system cmd.exe.

![Capture](https://user-images.githubusercontent.com/5764917/75111961-3dbcbe80-567a-11ea-8044-554e9fa7c452.PNG)

**Comment by m4wayne** [comment]
It's ok, thx!

Installing 'neteasemusic' (2.7.1.198242) [64bit]
Loading cloudmusicsetup2.7.1.198242.exe from cache
Checking hash of cloudmusicsetup2.7.1.198242.exe ... ok.
Extracting dl.7z ... done.
Linking D:\Apps\Scoop\User\apps\neteasemusic\current => D:\Apps\Scoop\User\apps\neteasemusic\2.7.1.198242
Creating shim for 'cloudmusic'.
Creating shortcut for 网易云音乐 (cloudmusic.exe)
Running post-install script...
'neteasemusic' (2.7.1.198242) was installed successfully!
