### ISSUE TITLE
wechat@2.6.7: hash check failed

### ISSUE THREAD

**Issue by yanshibin** [h404bi/dorado#8]
Installing 'wechat' (2.6.7) [64bit]
WeChatSetup.exe (42.1 MB) [===============================================================================] 100%
Checking hash of WeChatSetup.exe ... ERROR Hash check failed!
App:         dorado/wechat
URL:         https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe#/dl.7z
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    8ec2976e5b7d5e195b823ff054a08bcfedb3517cd31f8163263b1999a2a9a29b
Actual:      fb77dd957bd07afae84ca144d7fd334447a5bc983bb25a4046dd3afaf467bfc3

**Comment by h404bi** [comment]
Fixed in https://github.com/h404bi/dorado/commit/795b33ec30e2889c9fdac04597c987283ef52c47
