### ISSUE TITLE
Request: Nutstore

### ISSUE THREAD

**Issue by Ni1fheim** [h404bi/dorado#88]
请求加一个坚果云😂😂😂

**Comment by h404bi** [comment]
经测坚果云需要启动系统服务（应该是用于同步），需要管理员权限，用 Scoop 安装会失去同步功能。

**Comment by Ni1fheim** [comment]
> 经测坚果云需要启动系统服务（应该是用于同步），需要管理员权限，用 Scoop 安装会失去同步功能。

是的，今天发现其实不用客户端，直接使用其自带的WebDAV协议把整个网盘挂载在文件系统上就可以了，Windows10本身是支持的，就相当与多了一个“分区”的样子，像这样：

![image](https://user-images.githubusercontent.com/31804253/76627160-76fb9680-6575-11ea-9d03-df9e2f28ef09.png)

**Comment by Ni1fheim** [comment]
> > 经测坚果云需要启动系统服务（应该是用于同步），需要管理员权限，用 Scoop 安装会失去同步功能。
> 
> 是的，今天发现其实不用客户端，直接使用其自带的WebDAV协议把整个网盘挂载在文件系统上就可以了，Windows10本身是支持的，就相当与多了一个“分区”的样子，像这样：
> 
> ![image](https://user-images.githubusercontent.com/31804253/76627160-76fb9680-6575-11ea-9d03-df9e2f28ef09.png)

个人也建议直接这样使用，出于备份或同步的目的都很好，把想备份的文件放到这个文件夹，就可以自动完成增量同步。
