### ISSUE TITLE
clash-for-windows@0.9.3: hash check failed

### ISSUE THREAD

**Issue by Abnerya** [h404bi/dorado#98]
Checking hash of Clash.for.Windows-0.9.3-win.7z ... ERROR Hash check failed!
App:         dorado/clash-for-windows
URL:         https://github.com/Fndroid/clash_for_windows_pkg/releases/download/0.9.3/Clash.for.Windows-0.9.3-win.7z
First bytes: 37 7A BC AF 27 1C 00 04
Expected:    8bab9fd169cd038f7d5ca96189a01e9a5289fa41fefe8fc58748c1fc2912a7ba
Actual:      2d34e3eb9efd4facd26638579b86bbdb00bb05127dc79d55b9444ab3a9250717

**Comment by lifansama** [comment]
#99

**Comment by escape0707** [comment]
And we don't use bot/script for auto updating app manifests? 🤔

**Comment by escape0707** [comment]
@Abnerya @lifansama Try this one liner for updating this time while waiting for the bucket owner to update the app manifest later:
```powershell
cd $env:userprofile\scoop\buckets\dorado; .\bin\checkver.ps1 -App clash-for-windows -u -f; scoop update clash-for-windows; git restore .\bucket\clash-for-windows.json
```

See [updating-manifest](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate#updating-manifest).

**Comment by zhoujin7** [comment]
这么快~~刚更新遇到问题

**Comment by zhoujin7** [comment]
哈哈 几乎同一个时间 执行update......
